---
title: "Academic Activities"
description: "Academic Activities"
title-block-banner: "#464646"
engine: knitr 
---

```{css, echo=FALSE}

#title-block-header .title {
    display: none;
}

#title-block-header .description {  /* Adapt based on the actual class or ID */
    color: white;
    font-size: 1.7em;  /* Adjust as needed */ 
    font-weight: bold;  /* Makes the text bold */
}

```

## Conferences and Workshops

-   September, 2026. American Political Science Association Annual Meeting. *Transnational Repression and Engagement: Evidence from a Panel of Russian Exiles*.
-   October, 2025. Ifo CEMIR Junior Workshop for Migration Research, Munich. *Reversing Brain Drain from Autocracies: How Autocratic Incentives, Regime Change, and Hostland Conditions Shape the Return of Political Emigrants*.
-   September, 2025. ZOiS ERDAM Conference "Emerging Russian Diasporas: Exploring New Dynamics and (Im)Mobilisation Patterns", Berlin. *Reversing Brain Drain from Autocracies: How Autocratic Incentives, Regime Change, and Hostland Conditions Shape the Return of Political Emigrants*.
-   June, 2025. European Political Science Association Annual Meeting, Madrid. *Reversing Brain Drain from Autocracies: How Autocratic Incentives, Regime Change, and Hostland Conditions Shape the Return of Political Emigrants*.
-   September, 2024. American Political Science Association Annual Meeting. *How to Maintain a Panel of Political Migrants: Evidence from a Field Experiment*.
-   July, 2024. European Political Science Association conference. *Can Migrant Organizations Evade the Long Arm of Autocrats? A Conjoint Experiment on Donation Preferences Among Russian Exiles*.
-   December, 2023. Association for Slavic, East European, and Eurasian Studies (ASEEES) Convention. *Can Migrant Organizations Evade the Long Arm of Autocrats? A Conjoint Experiment on Donation Preferences Among Russian Exiles*.
-   November, 2023. European Commission working group on mapping the New Russian Diaspora in Europe and the Neighbourhood. *Year and a Half in Exile: What Changed in the Lives of Russian Emigrants*.
-   September, 2023. Portulans Institute. Oxford Roundtable: How The Conflict In Ukraine Could Reshape Global Information, Communication, And Security. Topic presented: *The Role of Communication Networks Among Russian Emigrants in Shaping Political Discourse*.
-   April, 2023. XXII April International Academic Conference on Economic and Social Development, Higher School of Economics, Moscow. Topic presented: *Surveying Post-2022 Emigrants from Russia with OutRush Project: Methodological Issues and Limitations*.
-   February, 2023. ZOiS Workshop: Exploring the New Exodus from Russia: Migration, Adaptation and Transnational Engagement. Topics presented: a) *Six months in emigration: the emergence of transnational social networks among new Russian emigrants*. b) *Democracy in Exile? Estimating the Capacity for Collective Action among Russian Anti-War Migrants. Evidence from a Panel Survey*.
-   January, 2023. Robert Schuman Centre for Advanced Studies, Migration Working Group, European University Institute, Florence. Topic presented: *The effect of discrimination on the political behavior of recent migrants: evidence from two waves of the panel survey of new Russian migrants*.
-   December, 2022. Aleksanteri Institute, University of Helsinki: Elections after 2022: The Short and Long-Term Impact of the Russian Invasion of Ukraine. Topic presented: *Helping to flee a political crisis: a Conjoint Experiment of Russian Migrants*.
-   November, 2022. Robert Schuman Centre for Advanced Studies, Migration Working Group, European University Institute, Florence. Topic presented: *Solidarity Between New Russian Migrants: Evidence from a Conjoint Experiment*.
-   April, 2021. XXI April International Academic Conference on Economic and Social Development, Higher School of Economics, Moscow. Topic presented: *The Effects of Unhappiness on Preferences for Redistribution*.
-   October, 2020. X Grushin Sociological Conference, Moscow. Topic presented: *National Pride and Subjective Well-being of Russians*.
-   May, 2019. 4th International Russia Longitudinal Monitoring Survey of HSE User Conference. Higher School of Economics, University of North Carolina -- Chapel Hill, Moscow. Topic presented: *Subjective Well-being of Migrants in Russia: Effects of Regional Characteristics and Migration Legislation*.

## Additional Education

-   January, 2022. Global Corruption Workshop, Boris Nemtsov Foundation for Freedom.
-   September-December, 2018. Exchange student in Jyvaskyla University, Finland.
-   August 20-31, 2018 LCSR Summer School -- 2018 "Bayesian Statistical Analyses for Social Scientists".
-   June 26-29, 2018 Summer School on Migration organized by Russian Red Cross.

## Organization of Conferences and Workshops

-   April, 2021. [The First Ultimate Conference](http://1ultimateconference.tilda.ws). Standup Conference on Non-serious Topics, but with Serious Methods. European University in Saint Petersburg. Role: co-organizer and moderator.
-   
    2021. Spring School in Political Science. European University in Saint Petersburg. Role: co-organizer.
