---
title: "Projects"
description: "Research Projects"
title-block-banner: "#464646"
engine: knitr 
---

```{css, echo=FALSE}

#title-block-header .title {
    display: none;
}

#title-block-header .description {  /* Adapt based on the actual class or ID */
    color: white;
    font-size: 1.7em;  /* Adjust as needed */ 
    font-weight: bold;  /* Makes the text bold */
}

```

## Panel-survey of War-induced Russian Emigrants

I am the Principal Investigator for the [OutRush project](https://outrush.io/eng), a panel survey focused on Russian emigrants who left Russia after February 24, 2022. To date, we have collected data across three waves, involving a total of 10,000 respondents residing in more than 100 countries. The project employs a diverse range of research methods, including both experiments and qualitative interviews. Our collected data has received extensive media coverage, both in Russia and internationally. Media outlets that have cited our data include: 

In English: [Bloomberg](https://www.bloomberg.com/news/articles/2024-05-02/russians-who-fled-war-return-in-boost-for-putin-s-war-economy), [Financial Times](https://www.ft.com/content/5e6bcce9-7bda-4b29-b1b7-f7df6e879fd9), [Al Jazeera](https://www.aljazeera.com/news/2024/1/22/russian-exiles-unlikely-to-return), [Deutsche Welle](https://www.dw.com/en/russia-why-people-are-returning-despite-the-war-in-ukraine/a-67022321), [CNBC](https://www.cnbc.com/2022/11/25/georgia-armenia-turkey-economies-boom-with-russian-wealth-migration.html), [Fortune](https://fortune.com/europe/2022/08/20/russia-brain-drain-young-russians-leaving-after-ukraine-war-putin/), [The Moscow Times (1)](https://www.themoscowtimes.com/2023/10/25/15-of-russians-who-fled-war-mobilization-have-returned-survey-a82885), [The Moscow Times (2)](https://www.moscowtimes.ru/2023/01/19/sotsialnii-portret-novoi-volni-rossiiskih-emigrantov-a31239), [The Japan Times](https://www.japantimes.co.jp/news/2024/05/02/world/politics/russians-putin-war-economy/)

In Russian: [BBC](https://www.bbc.com/russian/features-65686712), [Deutsche Welle](https://www.dw.com/ru/sdelka-s-sovestu-pokinuvsie-rossiu-i-potom-vernuvsiesa-o-svoem-opyte/a-66896905), [Voice of America](https://www.instagram.com/p/Cy1WVu2LbYT/), [Meduza (1)](https://meduza.io/episodes/2023/07/10/chinovniki-uveryayut-mnogie-uehavshie-ot-voyny-rossiyane-mechtayut-vernutsya-obratno-a-kak-na-samom-dele-rasskazyvaet-sotsiolog-nika-kostenko), [Meduza (2)](https://meduza.io/feature/2022/12/23/uehavshie-rossiyane-stali-bednee-no-zato-teper-bolshe-doveryayut-lyudyam-i-veryat-v-buduschee), [Meduza (3)](https://meduza.io/feature/2022/07/31/chem-nyneshnyaya-volna-emigratsii-otlichaetsya-ot-drugih-predstaviteli-kakih-professiy-uehali-sobirayutsya-li-migranty-vernutsya), [RBC (1)](https://www.rbc.ru/spb_sz/29/01/2023/63ce99cc9a794787b4a2e9de), [RBC (2)](https://www.rbc.ru/politics/25/10/2023/6538b8739a7947719d23fd1e), [RBC (3)](https://www.youtube.com/watch?v=7NsNp4MoUJw&ab_channel=%D0%A0%D0%91%D0%9A%D0%98%D0%BD%D0%B2%D0%B5%D1%81%D1%82%D0%B8%D1%86%D0%B8%D0%B8), [Forbes Russia](https://t.me/forbesglobalrus/3396), [Zhivoy Gvozd](https://www.youtube.com/watch?v=Bvcfj9a9XH8&t=4028s), [Important Stories](https://istories.media/news/2023/10/25/v-rossiyu-mogli-vernutsya-bolee-15-uekhavshikh-posle-nachala-voini-schitayut-issledovateli/), [Rasstriga.doc](https://open.spotify.com/episode/3n2gfxhNFRaSmrK8BFzE5U), [Paper (1)](https://paperpaper.ru/kto-svyazyvaet-svoe-budushee-s-rossiej-b/), [Paper (2)](https://paperpaper.ru/emigranty-2022-go-ne-planiruyut-vozvrashat/), [Karèn Shainyan](https://youtu.be/VzaFzSVtDtA), [RTVI](https://rtvi.com/news/ft-bolee-15-rossijskih-emigrantov-vremenno-ili-nadolgo-vernulis-v-rossiyu/), [Novaya Gazeta](https://novayagazeta-ru.cdn.ampproject.org/c/s/novayagazeta.ru/amp/articles/2022/12/27/strana-ubytiia), [Sever Real](https://www.severreal.org/a/rabotaem-do-pervogo-donosa-chto-budet-s-naukoy-i-vysshim-obrazovaniem-/32127897.html), [VC](https://vc.ru/money/575523-den-313-kolichestvo-nevyezdnyh-iz-za-dolgov-rossiyan-k-novomu-godu-stalo-rekordnym-za-15-let), [Feminist Anti-War Resistance](https://syg.ma/@feminist-anti-war-resistance/uiekhavshiie-rossiianie-bolieie-fieministski-nastroieny-sotsiologhi-iz-proiekta-outrush-o-novoi-volnie-rossiiskoi-emighratsii), [Klops](https://klops.ru/other/2023-10-25/282009-15-relokantov-pokinuvshih-rossiyu-posle-nachala-svo-vernulis-domoy-issledovateli), [Vot Tak](https://vot-tak.tv/novosti/27-10-2023-demograf-dopustil), [Glagol](https://glagol.press/uchjonye-soobshhili-o-vozvrashhenii-v-rossiju-relokantov), [Grodno 24](https://grodno24.com/2023/10/uehavshie-iz-strany-posle-nachala-svo-rossiyane-massovo-vozvrashhayutsya-na-rodinu.html), [Komsomolskaya Pravda](https://www.kp.ru/daily/27573/4842340/), [Agents Media](https://www.agents.media/demograf-rasskazal-o-vozvrashhenii-v-rossiyu-do-poloviny-uehavshih-iz-rossii-v-2022-godu/)

In other languages: [Jungle.World (DE)](https://jungle.world/artikel/2023/03/die-kompetenten-werden-durch-die-loyalen-ersetzt), [Information (DA)](https://www.information.dk/udland/2023/02/stoerste-brain-drain-30-aar-ressourcestaerke-russere-antonina-startet-nyt-liv-udlandet), [Corriere Del Ticino (ES)](https://www.cdt.ch/news/erano-scappati-dalla-guerra-ora-stanno-tornando-a-casa-331807), [Ceske Noviny (CS)](https://www.ceskenoviny.cz/zpravy/rusove-kteri-po-unoru-odjeli-z-vlasti-zacali-podle-pruzkumu-vice-verit-lidem/2302793), [Pravda (SK)](https://spravy.pravda.sk/svet/clanok/651763-rusi-ktori-po-februari-odisli-z-vlasti-zacali-podla-prieskumu-viac-verit-ludom/)



Based on this data, we have published several media and [policy papers](https://outrush.io/eng#results) and are currently preparing multiple academic papers.

## Intimate Partner Violence in Russia

I am the Principal Investigator for the [Violence Monitor project](https://violencemonitor.org/), a series of surveys focused on intimate partner violence conducted in Russia in 2021. The project encompasses various research methods, including several survey and field experiments designed to enhance the disclosure of intimate partner violence. Our work has received media coverage from outlets such as [Forbes Russia](https://www.forbes.ru/forbes-woman/486866-ab-uz-slepki-kontrol-bolee-20-mln-rossian-stalkivalis-s-partnerskim-nasiliem?fbclid=IwAR0fhPrnwjVvDhSfNmFkEqGFkm4hZ7Obo-l43AkxMrDs3RK2mwwfB4M0jA4), [Moscow FM](https://www.mosfm.com/audios/151399), [PaperPaper](https://paperpaper.io/bil-unizhal-zastavlyal-kto-chashe-stalkiv/), [Holod](https://holod.media/2023/03/08/partnerskoe-nasilie/), and others (see more [here](https://violencemonitor.org/media)). We have published a report on measuring violence and its prevalence rates in Russia [here](https://drive.google.com/file/d/1fpdVeTnYBz56nMcaAnOYND_wQ-1ATB0y/view) and are currently in the process of preparing several academic papers.

## Corruption Tolerance

I served as a Research Assistant in a project led by [Miriam Golden](https://www.miriamgolden.com/), [Raymond Fisman](https://sites.bu.edu/fisman/), and [Matteo Ferroni](https://www.matteo-ferroni.com/). The project aimed to measure perceptions and norms of corruption among legislators and citizens in three countries: Colombia, Italy, and Pakistan. My responsibilities included conducting descriptive statistics and managing recruitment. For the recruitment process, I automated email communications using R.
