---
title: "Publications and Media"
description: "Publications and Media"
title-block-banner: "#464646"
engine: knitr 
---

```{css, echo=FALSE}

#title-block-header .title {
    display: none;
}

#title-block-header .description {  /* Adapt based on the actual class or ID */
    color: white;
    font-size: 1.7em;  /* Adjust as needed */ 
    font-weight: bold;  /* Makes the text bold */
}


```

## Job Market Paper

[Unintended Consequences of Transnational Repression: How Opposition Gains Support Abroad in Response to Criminalization by Autocrats](https://drive.google.com/file/d/1SkUJsYpNjOZ-HL9hM9QaIda1OWeEq1cO/view?usp=sharing), with Ivetta Sergeeva

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Autocrats often use legal repression to criminalize opposition organizations, targeting both domestic and exile groups to suppress dissent. While such measures may weaken cooperation with these organizations domestically, these organizations can simultaneously gain increased support from migrant communities. This study explores whether autocrats achieve their intended outcomes by legally repressing exile organizations through criminalization. Utilizing a conjoint experiment with 5,996 Russian emigrants residing in 89 countries who left their homeland following the 2022 invasion of Ukraine, we investigate how attributes such as criminalization, anonymity of donations, and transparency influence their cooperation with exile organizations in a geopolitically shaped environment. Our findings show that criminalization can backfire: Russian exiles perceive it as a marker of political authenticity and effectiveness, providing crucial cues in an environment with limited information and fostering solidarity. Consequently, criminalization can facilitate collective action and the coordination of extraterritorial opposition, signaling which organizations are genuinely committed to opposing the regime. However, geopolitical alliances matter, as cooperation is hindered where perceived risks are high, particularly in host countries allied with the autocrat. Technological solutions, such as anonymous donations, significantly mitigate these risks and boost support, while transparency is key to engaging the most politically active donors. This study contributes to understanding the limits of autocratic transnational control and demonstrates how exile organizations can leverage low-cost measures to foster diaspora’s resilience and address problems of collective action and coordination.* -->

<!-- </details> -->

## Peer-Reviewed Publications

["Helping to Flee a Political Crisis: How Antiwar Alignment Shapes the Aid Preferences of Wartime Russian Migrants"](https://drive.google.com/file/d/1Nwox_BE_15nwqmmSDZjLt1FmQeHixvUp/view?usp=drive_link), with Ivetta Sergeeva. In *Perspectives on Politics* (2025) (Conditionally accepted)

["Invisible Costs of Exiting Autocracy: Subjective Well-being and Emotional Burnout Among Russian Wartime Migrants"](https://www.tandfonline.com/doi/full/10.1080/1060586X.2025.2477417), with Ivetta Sergeeva, *Post-Soviet Affairs* (2025)

["Gender Egalitarianism of Recent Emigrants from Russia: The Effect of Emigration or a Trait of a Social Group?"](https://online.ucpress.edu/cpcs/article-abstract/doi/10.1525/cpcs.2025.2480442/212148/Gender-Egalitarianism-of-Recent-Emigrants-from?redirectedFrom=fulltext), with Veronica Kostenko and Ivetta Sergeeva, *Communist and Post-Communist Studies* (2025)

["Voice after Exit? Exploring Patterns of Civic Activism among Russian Migrant Communities in Eurasia after 24 February 2022"](https://hup.fi/site/chapters/e/10.33134/HUP-26-8/), with Margarita Zavadskaya and Ivetta Sergeeva. In *Global Migration and Illiberalism in Russia, Eurasia and Eastern Europe*, Helsinki University Press, 2024

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Can citizens continue to participate in the politics of their home country after migrating to another country? Many examples exist of migrants engaging in their countries of origin's political affairs, such as expatriate voting, forming political communities and hometown associations, donating money to political movements and politicians, advocating for migrants' rights, and other forms of political participation. However, it remains unclear why migrants are willing to continue exercising their ‘voice’ after ‘exit’ and what the main challenges and obstacles are for them to do so while abroad. In this chapter, we analyze the patterns of civic and political engagement among Russian migrants who fled their home country following the invasion of Ukraine in February 2022. Drawing on scholarship in migration studies, we view exit and voice not as mutually exclusive but as mutually reinforcing alternatives. We argue that the way migrants connect with their homeland plays a crucial role in mobilizing and demobilizing them, particularly the connections they have with their employers. The incentives provided by employers may force migrants to dampen their propensity to engage in political activities. To support our argument, we rely on an original survey conducted in March-April and September 2022, as well as semi-structured, in-depth interviews conducted in Georgia, Kazakhstan, Kyrgyzstan, Armenia, and Turkey.* -->

<!-- </details> -->

**In Russian:**

[Factors of mass support for the government in the times of structural reforms](http://inion.ru/en/publishing/journals-recommended-by-the-high-certification-commission/political-science-old/arkhiv/2021-2-institutcional-nye-reformy/faktory-massovoi-podderzhki-pravitel-stva-v-usloviiakh-provedeniia-strukturnykh-reform-factors-of-mass-support-for-government/). Political science (RU), 2021, with Boris Sokolov, Margarita Zavadskaya

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Any country in order to stay afloat sooner or later is forced to under-take large-scale internal reforms in various policy areas. However, structural reforms often bear adverse consequences for the population. As the studies of the US and Euro-pean states show, one of the most crucial negative consequences is the decrease in mass support for the government that has initiated the reform. The latter manifests itself in a drop of approval ratings, trust in government, propensity to vote for the incumbent at the forthcoming elections. Such a decrease may lead to decreased legitimacy of the political power, thereby destabilizing the current political system. Is it possible to strike the balance between the necessity of reform and upholding trust on the society’s be-half? Can a government carry out painful reforms without provoking hatred? What conditions facilitate such balance? Although the factors of mass support play the central role in nowadays’ political science, the answers to the questions mentioned above re-main unanswered. This article examines different options available to governments in order to preserve their mass support and legitimacy when conducting unpopular re-forms, with a special emphasis on media framing. Using various theoretical sources and the recent literature on political support in Russia, it identifies various factors that may facilitate the use of the latter option in the Russian context.* -->

<!-- </details> -->

[National Pride and Subjective Well-being of Russians](https://www.ssoar.info/ssoar/handle/document/74840). Monitoring of Public Opinion: Economic and Social Changes, with E. Ponarin

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Since the beginning of the 2000s, subjective well-being of the Russians was growing due to growing incomes and strengthening optimism about the future. However, the worsening economic situation following the crisis in 2008 did not cause the expected fall in subjective well-being rates. One plausible explanation is the growth of national pride. In this paper, it is tested whether or not national pride positively and causally affect happiness and life satisfaction of Russians. Possible compensatory properties of national pride - its hypothetical stronger effect for individuals with low incomes and poor health - are also being investigated. Data: integrated database of the World Values Survey and the European Values Study containing survey data for Russia from 1990 to 2017. Methods: linear regression with instrumental variables. Results: the effect of national pride on subjective well-being is positive and statistically significant (β = 0.26, p-value \<0.001), the effect persists while using instrumental variables (β = 0.92, p-value \<0.001); the effect is stronger in the period after 2008, as well as for people with low incomes.* -->

<!-- </details> -->

[Subjective Well-being of Migrants in Russia: Effects of Regional Characteristics and Migration Legislation](https://demreview.hse.ru/index.php/ecsoc/article/view/10407), Journal of Economic Sociology, with E. Ponarin

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Migration is an important and rapidly growing phenomenon in the modern world. Many countries are facing problems with integration and adaption of migrants to new living conditions. Subjective well-being (SWB) can be considered as an indicator of how successfully migrants are adapted and integrated into the host society. Levels of migrants’ SWB are often determined by the same factors as for other people—good health, high salary, employment and youth make them happier. Nonetheless, migrants’ decision to migrate is often led by economic motives, which leads them to overvalue economic characteristics of countries and regions of destination and undervalue non-economic factors. This paper aims to estimate the effects of the economic prosperity (measured by gross regional product) and social capital of Russian regions (measured by general social trust and relative size of the community of the migrant’s compatriots) on the life satisfaction of migrants. In addition, we analyze possible effect of the inclusion of the migrants’ country of origin into Eurasian Customs Union. To answer the proposed questions we employed data of the Russian Longitudinal Monitoring Survey—Higher School of Economics (RLMS-HSE) and statistics provided by Russian Federal State Statistics Service. The main method of analysis is a cross-classified multilevel linear regression modeling. The results show that the economic performance of a region has no effect on the life satisfaction of a migrant. It appears that social factors play a greater role—the effects of general social trust and the relative size of the community of a migrant’s compatriots in a region are positive and statistically significant. We found that inclusion of the country of migrants’ origin into the Eurasian Customs Union positively and significantly affects the life satisfaction of migrants. We associate this effect with a decrease in the economic and psychological costs of migration.* -->

<!-- </details> -->

## Revise and Resubmit


["Measuring Intimate Partner Violence in Middle-Income country: Evidence from Series of List Experiments and Self-Administered Surveys"](https://drive.google.com/file/d/1W_YbiAa7VgFQ26PWyFKXYzMJjelVoifn/view?usp=sharing), with Ivetta Sergeeva (*Sociological Methods and Research*)

<!-- <details> -->

<!-- <summary>Abstract</summary> -->

<!-- *Intimate Partner Violence (IPV) is a multifaceted issue that has seen a concerning rise during the global COVID-19 pandemic. While accurate data on IPV prevalence is essential for targeted interventions, traditional administrative data often falls short due to the private nature of IPV and victims' hesitance to seek aid. Sociological surveys, though promising, grapple with challenges like social desirability bias. This study, set against the backdrop of Russia—a country with sparse reliable IPV data—compares various IPV measurement approaches with the face-to-face survey as the benchmark. Our findings reveal that online surveys, devoid of enumerator presence, most effectively capture IPV prevalence rates in Russia. Specifically, these online methods outperformed list experiments and self-administered questionnaires. Notably, women demonstrated a higher IPV disclosure rate in online surveys compared to face-to-face interviews. This research not only underscores the importance of methodological considerations in IPV data collection but also emphasizes the superior efficacy of online surveys in capturing genuine IPV experiences, especially among women.* -->

<!-- </details> -->


## Papers in Progress (available on request)

"How to Maintain a Panel of Political Migrants: Evidence from a Field Experiment", with Ivetta Sergeeva

"Can Media Framing Increase Support for Health Reform? Results of the Conjoint Experiment", with Boris Sokolov, Margarita Zavadskaya and Ivetta Sergeeva

"Gendered Response to War: Explaining Gender Gap in Political Activism of Wartime Russian Emigrants, 2022-2023", with Karolina Nugumanova and Ivetta Sergeeva

"The Effect of Discrimination on the Political Behavior of Recent Migrants: Evidence from Two Waves of the Panel Survey of New Russian Migrants", with Ivetta Sergeeva

## Policy Briefs and Media Columns

[Should I Stay or Should I Go? Russian Emigration in Flux](https://carnegieendowment.org/russia-eurasia/politika/2024/07/russian-emigration-in-flux?lang=en&center=russia-eurasia), *Carnegie Politika*, 2024, with Ivetta Sergeeva

Policy brief, [Far from Home: Russians Relocating to Latin America](https://www.ponarseurasia.org/far-from-home-russians-relocating-to-latin-america/), *Ponars Eurasia*, with Svetlana Ruseishvili and Ivetta Sergeeva

Research report, [A Year and a Half in Exile: Progress and Obstacles in the Integration of Russian Migrants](https://osf.io/preprints/socarxiv/ckf4v), *SocArXiv*, 2024, with Ivetta Sergeeva

Policy brief, [In their Own Voice: Supporting Russia’s Wartime Migrants](https://www.ponarseurasia.org/in-their-own-voice-supporting-russias-wartime-migrants/), *Ponars Eurasia*, with Rergina Smyth, Ivetta Sergeeva, Margarita Zavadskaya, Veronica Kostenko, Michail Turchenko, Andrey Semenov

Research report, [Six Months in Exile: A New Life of Russian Emigrants](https://osf.io/preprints/socarxiv/epn2c/). *SocArXiv*, 2023, with Ivetta Sergeeva, Veronica Kostenko, Margarita Zavadskaya

Policy brief, [New Russian Migrants Against the War: Political Action in Russia and Abroad](https://library.fes.de/pdf-files/international/20458.pdf). *Friedrich-Ebert-Stiftung*, 2023, with Ivetta Sergeeva, Margarita Zavadskaya, Veronica Kostenko

Research report, [Studying Public Opinion Among Migrants: Challenges and Opportunities](https://www.ssoar.info/ssoar/bitstream/handle/document/86786/ssoar-russanald-2023-292-kamalov_et_al-Studying_Public_Opinion_Among_Migrants.pdf?sequence=1&isAllowed=y&lnkname=ssoar-russanald-2023-292-kamalov_et_al-Studying_Public_Opinion_Among_Migrants.pdf). *Russian Analytical Digest*, 2023, No. 292, with Ivetta Sergeeva, Margarita Zavadskaya, Veronica Kostenko

[The Russian Rhizome: a Social Portrait of New Immigrants](https://re-russia.net/en/expertise/045/). *Re-Russia*, 2023, with Ivetta Sergeeva, Veronica Kostenko, Margarita Zavadskaya

[New Activists or New 'Common Folk?' The Evolution of Political Activism Among Russian Anti-war Emigrants](https://russiapost.info/society/common_folk). *Russia.Post*, 2023, with Ivetta Sergeeva, Margarita Zavadskaya, Veronica Kostenko

[Abuse, Slapping, Control: More than 20 Million Russians have Experienced Partner violence](https://www.forbes.ru/forbes-woman/486866-ab-uz-slepki-kontrol-bolee-20-mln-rossian-stalkivalis-s-partnerskim-nasiliem). *Forbes Russia*, 2023, with Ivetta Sergeeva (in Russian)

Research report, [Partner Violence in Russia: Results of a Series of Surveys](https://violencemonitor.org/report_2023), *Violencemonitor.org*, 2023, with Ivetta Sergeeva (in Russian)

Research report, [The Great Exodus: A Portrait of New Migrants from Russia. Report on the results of the March 2022 survey](https://outrush.io/report_march_2022). *OutRush*, 2022, with Ivetta Sergeeva, Veronica Kostenko, Margarita Zavadskaya

Policy brief, [Russia's 2022 Anti-War Exodus: The Attitudes and Expectations of Russian Migrants](https://www.ponarseurasia.org/russias-2022-anti-war-exodus-the-attitudes-and-expectations-of-russian-migrants/). *Ponars Eurasia*, 2022, with Ivetta Sergeeva, Veronica Kostenko, Margarita Zavadskaya

## Interviews

[Новая русская эмиграция: кто, куда и зачем уезжает из России сегодня](https://open.spotify.com/episode/3n2gfxhNFRaSmrK8BFzE5U). *Юра, мы всё узнали* (Podcast), 2023.

[Эмигранты 2022-го не планируют возвращаться в Россию. Как изменилась их жизнь за полгода? Результаты большого исследования](https://paperpaper.ru/emigranty-2022-go-ne-planiruyut-vozvrashat/). *Бумага*, 2023.

[Det største brain drain i 30 år: Ressourcestærke russere som Antonina har startet et nyt liv i udlandet](https://www.information.dk/udland/2023/02/stoerste-brain-drain-30-aar-ressourcestaerke-russere-antonina-startet-nyt-liv-udlandet). *Information* (Denmark), 2023.

[Более 20 миллионов россиян сталкивались с партнерским насилием](https://www.mosfm.com/audios/151399). *Москва FM*, 2023.

[Young scholars in our professional team: interview for university page](https://spb.hse.ru/en/ma/econasia/news/382861781.html). *Higher School of Economics*, 2020.
